### ISSUE TITLE
Construct meta modules using the classes like post modules

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#139]
- [x] Move Delete Comment Meta
- [x] Integrate Delete Comment Meta Pro
- [x] Move Delete Post Meta (Handled in #271 )
- [x] Move Delete User Meta (Handled in #272)
- [x] Remove old code
- [ ] Test Delete Comment Meta
- [ ] Test Delete Post Meta
- [ ] Test Delete Post Meta Pro
- [ ] Test Delete User Meta
- [ ] Test Delete User Meta Pro

**Comment by sudar** [comment]
Testing will be done as part of #303
