### ISSUE TITLE
Add tests for Deleting Posts

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#156]
- [ ] https://github.com/sudar/bulk-delete/issues/188 Delete posts by Post status
- [ ] https://github.com/sudar/bulk-delete/issues/189 Delete posts by Custom Post status
- [ ] https://github.com/sudar/bulk-delete/issues/190 Delete posts by Custom Taxonomy
- [ ] https://github.com/sudar/bulk-delete/issues/191 Delete posts by Custom Post Type
- [ ] https://github.com/sudar/bulk-delete/issues/192 Delete posts by URL
- [ ] https://github.com/sudar/bulk-delete/issues/193 Delete posts by Revision

**Comment by sudar** [comment]
Closing this out and we will track all the sub tasks separately.
