### ISSUE TITLE
Add the ability to delete Term meta

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#247]
- [x] Add a new module called `Delete Term Meta` in the `Delete Meta Fields` page.
- [x] Show a list of available taxonomies. Use single select dropdown for this. Create a render method in `Renderer` if nothing is available already.
- [x] Once the user chooses the taxonomy, show the list of terms associated with that taxonomy. Use multi-select dropdown for this. Create a render method in `Renderer` if nothing is available already.
- [x] Show a list a unique meta keys for the taxonomy. Use a single select dropdown. Create a helper function in `Fetcher` to get the list of unique keys. Create a helper method in `Renderer` class to render this dropdown
- [x] Show a list of operations in a single select dropdown. Possible options are the following. We can add more later.
a) Equals to
b) Not Equals to
- [x] Add a textbox to enter the values.
- [x] Use Term Meta Query to retrieve the terms and then loop over them to delete the term meta data.

PR: https://github.com/sudar/bulk-delete/pull/445

**Comment by sudar** [comment]
Missed it in June 19th milestone. Moving now to June 26th milestone.

**Comment by rajanit2000** [comment]
@sudar i have one issue. If term meta value is contained array how can we delete it? How can we check the value equals or not equal?

**Comment by rajanit2000** [comment]
Status: Not yet started

**Comment by rajanit2000** [comment]
@sudar i have one issue. If term meta value is contained array how can we delete it? How can we check the value equals or not equal?

**Comment by sudar** [comment]
@rajanit2000 

Let's skip array values for now.

**Comment by rajanit2000** [comment]
Missed by this sprint(17th July), It will be complete next sprint
Reason: Car plugin's wrong estimation

**Comment by rajanit2000** [comment]
Code is available #445

**Comment by sudar** [comment]
@esudalaimadan 

Check the current status of this and see what else needs to be done to merge this.
