### ISSUE TITLE
Delete Post Meta - Migrate to new architecture

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#271]
- [x] Migrate Delete Post Meta
- [x] Manually Test the changes
- [x] Manually Test that the Delete Post Meta Pro add-on works

## Tests

- [x] Add tests for deleting single Post meta from the default 'Post' post type
- [x] Add tests for deleting more than two Post meta from the default 'Post' post type
- [x] Add tests for deleting single Post meta from the custom post type
- [x] Add tests for deleting more than two Post meta from the  custom post type
- [x] Add tests to restrict Post meta deletion based on post published date (older than option)
- [x] Add tests to restrict Post meta deletion based on post published date (posted within option)
- [x] Add tests for deleting Post meta from posts in batches
