### ISSUE TITLE
Delete User Post Meta - Migrate to new architecture

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#272]
- [x] Migrate User Post Meta
- [x] Manually Test the changes
- [ ] Manually Test that the User User Meta Pro add-on works

## Tests

- [x] Add tests for deleting single user meta fields from 'admin' user role
- [x] Add tests for deleting single user meta fields from 'subscriber' user role
- [x] Add tests for deleting multiple user meta fields from 'admin' user role
- [x] Add tests for deleting multiple user meta fields from 'subscriber' user role
- [x] Add tests for deleting user meta from users in batches
