### ISSUE TITLE
Delete Post Meta module - Use helper functions to render post type filter

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#288]
- [x] Use helper function to render post type filter
- [x] Add cron name (post meta and user meta)
- [x] Add PHPDoc block comments to all the test cases (post meta, user meta)
- [x] See if any other filters can be created using helper functions for the meta modules (post meta, user meta and comment meta)
