### ISSUE TITLE
Changes to Delete Post Meta Module

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#312]
- [x] Replace Post Type radio buttons to Post Type Select2 dropdown. Use `render_post_type_dropdown` in `PostsModule` helper function. If the helper function is not accessible in `MetasModule`, then move the `render_post_type_dropdown` function from `PostModule` to `Renderer` class which is the parent class of all these classes.
- [x] Replace the Post Type radio buttons to Post Type Select2 dropdow for DeleteComment Meta Module as well.
- [x] The filters are not working. Looks like a JS issue
- [x] Test all the filters without the add-on
- [x] Install add-on and test all the filters.
