### ISSUE TITLE
Changes to Delete User Meta Module

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#313]
- [x] Replace user role slug with user role name. Also create a helper function to display all user roles as radio buttons. The helper function should be moved to `Renderer` class.
- [x] The filters are not working. Looks like a JS issue
- [ ] Test all the filters without the add-on
- [ ] Install add-on and test all the filters.
