### ISSUE TITLE
Delete user meta - Add additional tests

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#330]
Add these additional tests to the Delete User Meta module.

- [x] Test deletion of user metas from more than one users in a single role.
- [x] Test deletion of user metas from more than role, with easy role having one user
- [x] Test deletion of user metas from more than role, with easy role having more than one user
- [x] Test deletion of user metas from one role, which has no users. Nothing should be deleted.
- [x] Test deletion of user metas from more than one role, where each role has no users. Nothing should be deleted.
- [x] Test deletion of user metas from more than one role, where one role doesn't have any users and other role has users. Nothing should be deleted.
- [x] Test deletion of user metas with both meta key and value (might require add-on for this)
