### ISSUE TITLE
Delete Comment Meta - Add tests

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#331]
Add tests for deleting comment meta

Do the following for built-in post type and then separately for a custom post type

- [x] Test deleting comment meta from one comment
- [x] Test deleting comment meta from more than one comment
- [x] Test deleting comment meta from one comment using meta value as well
- [x] Test deleting comment meta from more than one comment using meta value as well
- [x] Test deleting comment meta from more than one comment using meta value as well with different operations.
- [x] Test date filter
- [x] Test deletion in batches
- [ ] Test scheduling of deletion

**Comment by rajanit2000** [comment]
@sudar Its blocked by the filter register issue
https://github.com/sudar/bulk-delete/blob/1658b127e6d9b4a531e47dbb0aae450b333dcaee/include/Core/Metas/Modules/DeleteCommentMetaModule.php#L42
