### ISSUE TITLE
Delete Term meta - Add tests

### ISSUE THREAD

**Issue by sudar** [sudar/bulk-delete#350]
- [x] Delete default taxonomy term meta with equal value
- [x] Delete default taxonomy term meta with not equal value
- [ ] Delete custom taxomomy term meta with equal value
- [ ] Delete custom taxomomy term meta with not equal value

**Comment by rajanit2000** [comment]
Status: Not yet started

**Comment by rajanit2000** [comment]
Missed July 10th milestone 
Not started yet - the wrong estimation

**Comment by rajanit2000** [comment]
Missed current sprint (17th July), 
It will be complete (next sprint)
Reason for the delay: Car plugin wrong estimation

**Comment by sudar** [comment]
This will be done as part of #247
