### ISSUE TITLE
Refactor messages in meta modules

### ISSUE THREAD

**Issue by esudalaimadan** [sudar/bulk-delete#634]
- [x] Refactor validation,confirmation and success messages in DeleteCommentMeta Module
- [x] Refactor validation,confirmation and success messages in DeletePostMeta Module
- [x] Refactor validation,confirmation and success messages in DeleteUserMeta Module

PR https://github.com/sudar/bulk-delete/pull/643
